// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RUCsa.App.Persistencia;

namespace RUCsa.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("RUCsa.App.Dominio.Persona", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Restauranteid")
                        .HasColumnType("int");

                    b.Property<string>("apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("edad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estadocovid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("identificacion")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Restauranteid");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("RUCsa.App.Dominio.Restaurante", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("aforo")
                        .HasColumnType("int");

                    b.Property<string>("menu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numero_mesas")
                        .HasColumnType("int");

                    b.Property<int>("personas_por_mesa")
                        .HasColumnType("int");

                    b.Property<string>("tunos")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Restaurantes");
                });

            modelBuilder.Entity("RUCsa.App.Dominio.Turno", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("hora_asistencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("menu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("persona")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("RUCsa.App.Dominio.Administrativo", b =>
                {
                    b.HasBaseType("RUCsa.App.Dominio.Persona");

                    b.Property<string>("dependencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("oficina")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Administrativo");
                });

            modelBuilder.Entity("RUCsa.App.Dominio.Estudiante", b =>
                {
                    b.HasBaseType("RUCsa.App.Dominio.Persona");

                    b.Property<string>("programa")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Estudiante");
                });

            modelBuilder.Entity("RUCsa.App.Dominio.Personal_Aseo", b =>
                {
                    b.HasBaseType("RUCsa.App.Dominio.Persona");

                    b.Property<string>("turno_servicio")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Personal_Aseo");
                });

            modelBuilder.Entity("RUCsa.App.Dominio.Personal_Cocina", b =>
                {
                    b.HasBaseType("RUCsa.App.Dominio.Persona");

                    b.Property<string>("turno_servicio")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Personal_Cocina_turno_servicio");

                    b.HasDiscriminator().HasValue("Personal_Cocina");
                });

            modelBuilder.Entity("RUCsa.App.Dominio.Profesor", b =>
                {
                    b.HasBaseType("RUCsa.App.Dominio.Persona");

                    b.Property<string>("cubiculo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("facultad")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Profesor");
                });

            modelBuilder.Entity("RUCsa.App.Dominio.Persona", b =>
                {
                    b.HasOne("RUCsa.App.Dominio.Restaurante", null)
                        .WithMany("personas")
                        .HasForeignKey("Restauranteid");
                });

            modelBuilder.Entity("RUCsa.App.Dominio.Restaurante", b =>
                {
                    b.Navigation("personas");
                });
#pragma warning restore 612, 618
        }
    }
}
